[package]
name = "avion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
dotenvy = "0.15.7"
env_logger = "0.11.2"
log = "0.4.20"
poise = "0.6.1"
serenity = { version = "0.12.0", features = ["typesize"] }
strum = "0.26.1"
strum_macros = "0.26.1"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
