[package]
name = "avion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
const_format = "0.2.32"
dotenvy = "0.15.7"
poise = { git = "https://github.com/serenity-rs/poise", branch = "next" }
sentry = { version = "0.32.2", default-features = false, features = [
    "tokio",
    "panic",
    "backtrace",
    "contexts",
    "transport",
] }
sqlx = { version = "0.7", features = [
    "postgres",
    "runtime-tokio",
    "tls-native-tls",
] }
strum = "0.26.1"
strum_macros = "0.26.1"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[build-dependencies]
eyre = "0.6.12"
vergen = { version = "8.0.0", features = [
    "build",
    "git",
    "gitcl",
    "cargo",
    "rustc",
] }

[profile.release]
# Required for Sentry line numbers
debug = 1

# Decreases build times
[profile.dev.package.sqlx-macros]
opt-level = 3
