name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Run clippy
        run: cargo clippy --all-features -- -D warnings
      - name: Check formatting
        run: cargo fmt --check
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: avion-bot
          path: target/release/avion
          if-no-files-found: error
